spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/substation_db
    username: postgres
    password: 5EQnuNKY41r6
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080